name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ['Trigger Build']
    types: [completed]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch date
        id: date
        run: echo "DATE=$(date '%Y%m%d')" >> "$GITHUB_OUTPUT"
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8
          push: true # TODO: Only push on main
          tags: ghcr.io/fwcd/archlinuxarm-docker:latest,ghcr.io/fwcd/archlinuxarm-docker:${{ steps.date.outputs.DATE }}
